import type { NextPage } from 'next';
import Head from 'next/head';
import Podium from '../components/podium';
import { Restaurant } from '../types/restaurant';
import { getTopRestaurants } from '../utils/supabase';

interface HomeProps {
  topRestaurants: Array<Restaurant>;
}

const Home: NextPage<HomeProps> = ({ topRestaurants }) => {
  return (
    <div>
      <Head>
        <title>Reviews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Podium topRestaurants={topRestaurants} />
      </main>
    </div>
  );
};

export const getServerSideProps = async () => {
  const topRestaurants = await getTopRestaurants(3);

  return {
    props: { topRestaurants },
  };
};

export default Home;
